name: wisemade_app_core
description: Wisemade - Crypto Portfolio Management.

publish_to: none

version: 1.11.0+40

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  http: ^1.1.2
  flutter_session_manager: ^1.0.3
  intl: ^0.20.2
  timeago: ^3.3.0
  flutter_native_splash: ^2.4.0
  flutter_i18n: ^0.36.3
  mixpanel_flutter: ^2.2.0
  cupertino_icons: ^1.0.6
  skeletons: 0.0.3
  infinite_scroll_pagination: 5.0.0
  sliver_tools: ^0.2.12
  share_plus: ^10.0.0

  web3modal_flutter: ^3.1.2
  webview_flutter: ^4.13.0

  percent_indicator: ^4.2.3
  flutter_html: ^3.0.0-alpha.6
  flutter_launcher_icons: ^0.14.3
  flutter_hooks: ^0.21.2
  smooth_page_indicator: ^1.0.0+2

  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  url_launcher: ^6.2.2
  open_store: ^0.5.0
  email_validator: ^3.0.0
  easy_autocomplete: ^1.6.0
  jsonrpc2: ^3.0.1

  web3dart: ^2.7.3

  dotted_border: ^3.0.1
  dotted_decoration: ^2.0.0

  cached_network_image: ^3.3.0
  expandable_page_view: 1.0.17
  persistent_bottom_nav_bar: 6.2.1
  app_tracking_transparency: ^2.0.3
  favorite_button: ^0.0.4
  json_annotation: ^4.8.1
  flutter_uxcam: ^2.6.0
  uni_links: ^0.5.1
  screenshot: ^3.0.0
  provider: ^6.1.5
  path_provider: ^2.0.15
  mobile_scanner: ^7.0.0
  flutter_keyboard_visibility: 6.0.0
  upgrader: ^11.4.0
  shared_preferences: ^2.2.2
  syncfusion_flutter_charts: ^29.2.5
  webview_flutter_android: 4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.0

flutter_icons:
  android: true
  ios: true
  image_path: images/launcher-icon.png
  min_sdk_android: 21
  web:
    generate: true
    image_path: images/launcher-icon.png
    background_color: '#ffffff'
    theme_color: '#ffffff'
  windows:
    generate: true
    image_path: images/launcher-icon.png
    icon_size: 48

flutter:

  uses-material-design: true

  assets:
    - images/
    - i18n/